name: Github Pages

on:
  push:
    branches:
      - source # your source branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 16
      
      - name: checkout boilerplate
        uses: actions/checkout@v2
        with:
          repository: DiscreteTom/dt-blog-boilerplate
          path: boilerplateRepo
          persist-credentials: false

      - name: checkout blog
        uses: actions/checkout@v2
        with:
          ref: source # your source branch name
          path: contentRepo
          persist-credentials: false

      - name: install & generate
        run: |
          cp -r contentRepo/* boilerplateRepo
          cd boilerplateRepo/dt-blog-boilerplate
          yarn
          yarn generate

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Github token, which is automatically provided to the action.
          # You don't need to define this secret in your repo settings.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master # target branch
          publish_dir: boilerplateRepo/dt-blog-boilerplate/dist
